name: Daily donate in 12306

on:
  push:
    branches:
      - master
  workflow_dispatch: 
  schedule:
    - cron: '00 1 * * *'

jobs:
  dy_auto_donate_helper:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: 'Install requirements'
        run: pip install -r requirements.txt
      - name: 'Set driver'
        run: sudo cp -p ./chrome/chromedriver /usr/bin | sudo chmod -R 777 /usr/bin/chromedriver
      - name: 'Working'
        env:
          COOKIES: ${{ secrets.COOKIES }}
          SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}
        run: |
          sudo cp -p ./chrome/chromedriver /usr/bin/
          chmod -R 777 /usr/bin/chromedriver
          python main.py
